version: '3.8'

services:
  app:
    build: ./back
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    volumes:
      - ./ui:/usr/share/nginx/html
    ports:
      - "80:80"
